# -*- coding: utf-8 -*-
"""PredictionScript.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAUUqlvjMl2Tsn04g1X2SO949NeekqiI
"""

from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import sys

def main(imagepath):
    labelNames = ['APPLE', 'APPLE_JUICE', 'ASPARAGUS', 'AUBERGINE', 'AVOCADO', 'BANANA', 'BEANS', 'CABBAGE', 'CAKE', 'CANDY', 'CANTALOUPE', 'CARROT', 'CEREAL', 'CHIPS', 'CHOCOLATE', 'COFFEE', 'CORN', 'CUCUMBER', 'FISH', 'FLOUR', 'GALIA_MELON', 'GARLIC', 'GINGER', 'GRAPEFRUIT_JUICE', 'GREEN_PEPPER', 'HONEY', 'HONEYDEW_MELON', 'JAM', 'JUICE', 'KIWI', 'LEEK', 'LEMON', 'LIME', 'MANGO', 'MILK', 'MUSHROOM', 'NECTARINE', 'NUTS', 'OAT_MILK', 'OAT_YOGHURT', 'OIL', 'ONION', 'ORANGE', 'ORANGE_AND_GRAPEFRUIT_JUICE', 'ORANGE_JUICE', 'ORANGE_PEPPER', 'PAPAYA', 'PASSION_FRUIT', 'PASTA', 'PEACH', 'PEAR', 'PINEAPPLE', 'PLUM', 'POMEGRANATE', 'POTATO', 'RED_BEETROOT', 'RED_GRAPEFRUIT', 'RED_PEPPER', 'RICE', 'SATSUMA', 'SODA', 'SOUR_CREAM', 'SOUR_MILK', 'SOY_MILK', 'SOY_YOGHURT', 'SPICES', 'SUGAR', 'SWEET_POTATO', 'TEA', 'TOMATO', 'TOMATO_SAUCE', 'VINEGAR', 'WATER', 'WATERMELON', 'YELLOW_PEPPER', 'YOGHURT', 'ZUCCHINI']

    print ("Loading Network...")
    model = load_model("Models\kerasModelCompelete.h5")
    print ("Network Loaded.")

    imagePath = sys.argv[1]

    image = cv2.imread(imagePath)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    displayOutput = image

    image = cv2.resize(image, (96, 96))
    image = image.astype("float") / 255.0
    image = img_to_array(image)
    image = np.expand_dims(image, axis = 0)

    plt.rcParams["axes.grid"] = False
    plt.imshow(displayOutput.astype('uint8'))
    plt.show()

    print ("Classifying Image...")
    probabilities = model.predict(image)[0]

    likelinessThresh = 0.5
    outputArray = []

    for i in range(len(labelNames)):
        if (probabilities[i] >= likelinessThresh):
            ingredientsPair = []
            ingredientsPair.extend((labelNames[i], probabilities[i]))
            outputArray.append(ingredientsPair)

    print (outputArray)

    return outputArray

if __name__ == '__main__':
    main(sys.argv[1])